### ISSUE TITLE
Working with newer ruby versions and support for existing schema files

### ISSUE THREAD

**Issue by ChrisKaun** [pnnl/nokogiri_schematron_builder#1]
Hey, 

found your gem while googling and tried to add it to my rails v13/ruby v3.1.2 app and it didn't work as the code on the readme throws a error in initializing the Schema instance:  
```shell script
irb(main):016:0> schema = Nokogiri::XML::Schematron::Schema.new(title: "Example schema") do
  ns(prefix: "ex", uri: "http://example.com/ns#")
  pattern(title: "Example pattern") do
    context("/") do
      require("ex:A") do
        permit("ex:B") do
          reject("ex:C")
        end
      end
    end
  end
endirb(main):017:1*       ns(prefix: "ex", uri: "http://example.com/ns#")
irb(main):018:1>     pattern(title: "Example pattern") do
irb(main):019:2*           context("/") do
irb(main):020:3*               require("ex:A") do
irb(main):021:4*                   permit("ex:B") do
irb(main):022:5*                       reject("ex:C")
irb(main):023:5>                   end
irb(main):024:4>               end
irb(main):025:3>           end
irb(main):026:2>       end
irb(main):027:1>   end
.../ruby/3.1.0/bundler/gems/nokogiri_schematron_builder-15537db85912/lib/nokogiri/xml/schematron/base.rb:92:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

Also does this gem support Schematron creation from an existing schema/.sch file?

**Comment by markborkum** [comment]
Hi @ChrisKaun, Thanks for reporting this issue and for your question.

The issue is caused because of the changes to the handling of positional and keyword arguments that were introduced by Ruby 3.0 (see https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ for details). The gem has been updated to reflect these changes and we a new version `0.1.3` has been pushed to RubyGems.

Currently, this gem does not support opening preexisting `.sch` files.
